### ISSUE TITLE
Rewrite backend of the project on node.js

### ISSUE THREAD

**Issue by afanasy** [akura-co/stebeneva.ru#1]

**Comment by raabbajam** [comment]
Hello @afanasy,
I have implemented / converted some of the features.
I have put a demo on my site http://folbek.me:3000 (contact me if it down, I will get it up again).

The thing is I still can  not figure out the GD library for node.js, so uploading, resizing image is still in the making.

You can check the nodejs branch for the code. If you need some more comment / code explanation, please tell me so.

Your feedback is welcome. :+1:

**Comment by afanasy** [comment]
Looks great!
For graphics you can use the sharp lib:

``` sh
sudo apt-get install libvips
npm install sharp
```

https://github.com/lovell/sharp
Also, please don't use semicolons.
Thanks!

**Comment by raabbajam** [comment]
Hey, since the PHP counterpart using GD. so I decided using it with package `node-gd`. This also to make sure we use the same API.

Anyway, I did some checking, I think everything is working now. 
Adding photos, deleting, saving config.
Please check it and give me your feedback.

I also leave some note in readme, https://github.com/akura-co/stebeneva.ru/tree/nodejs#stebenevaru

If you have any concern or other problem, please do not hesitate to contact me.
